openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Orders Service"
paths:
  /orders/create:
    post:
      summary: "Create a new order"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDto'
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
  /orders/byID:
    get:
      summary: "Find Orders by ID"
      parameters:
        - name: "id"
          in: "query"
          required: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
  /orders/byDateAndSum:
    get:
      summary: "Find Orders by date and sum"
      parameters:
        - name: "date"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "date"
        - name: "total"
          in: "query"
          required: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/OrderResponseDto'
  /orders/exceptAndPeriod:
    get:
      summary: "Find Orders within a date period, exception some"
      parameters:
        - name: "except"
          in: "query"
          required: true
          schema:
            type: "string"
        - name: "minDate"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "date"
        - name: "maxDate"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "date"
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/OrderResponseDto'
components:
  schemas:
    OrderDto:
      type: "object"
      properties:
        totalSum:
          type: "integer"
        orderDate:
          type: "string"
          format: "date"
        recipient:
          type: "string"
        deliveryAddress:
          type: "string"
        paymentType:
          type: "string"
        deliveryType:
          type: "string"
        productArt:
          type: "integer"
        productName:
          type: "string"
        quantity:
          type: "integer"
        productPrice:
          type: "integer"
    OrderResponseDto:
      type: "object"
      properties:
        id:
          type: "integer"
        orderNumber:
          type: "string"
        totalSum:
          type: "integer"
        orderDate:
          type: "string"
          format: "date"
        recipient:
          type: "string"
        deliveryAddress:
          type: "string"
        paymentType:
          type: "string"
        deliveryType:
          type: "string"
        productArt:
          type: "integer"
        productName:
          type: "string"
        quantity:
          type: "integer"
        productPrice:
          type: "integer"